### ISSUE TITLE
Sending max amount left over 0.000012 NANO for some reason

### ISSUE THREAD

**Issue by ThunderFD** [BananoCoin/natrium-android-wallet#12]
I had to send those 0.000012 again by pressing max amount and no issues then. (other than it didn't send some leftover raw)

not sure how this happened... maybe it has something to do with me having raw on the account? 

block 1: https://www.nanode.co/block/FDBD575285F9D8DD6A0D0C1A1B7B9FA465BA3B771CA3898F8CED62CA558B5135
block 2: https://www.nanode.co/block/B994A07AF075CE63CE2C2D1D22A1C4B85DCC49F8635D64DF51BB6C1E70CBA796

**Comment by bbedward** [comment]
Did you send as local currency or did you send as NANO?

**Comment by ThunderFD** [comment]
I don't think I've ever changed the currency in the send window so far
