### ISSUE TITLE
Manual input for paper wallet loading

### ISSUE THREAD

**Issue by fallerOfFalls** [BananoCoin/natrium-android-wallet#16]
Could there be an option to type (or paste) the seed or key in, instead of reading a QR code?

**Comment by rainbyte** [comment]
It also would be useful to have an option to scan a QR code from an image file, eg. if someone sends NANO as present via chat messages (I have seen this feature in Chinese payment software)

**Comment by bbedward** [comment]
Resolved in flutter version, which will soon be replacing this version.

https://github.com/AvengeMedia/natrium_wallet_flutter

(scanning QR from image file is a separate issue)
