### ISSUE TITLE
Option to use address book when sending

### ISSUE THREAD

**Issue by fallerOfFalls** [BananoCoin/natrium-android-wallet#7]
Currently the way to send to an address in "contacts" is via settings. Would be better UX if the option was available when you press "send".

**Comment by yekta** [comment]
You can type @ at the address section and get the list and continue typing for the name, we should make that more clear probably 🙂

**Comment by bbedward** [comment]
The option is available from send screen, simply type "@" in the address field to bring up the list. Maybe it could be mentioned somewhere so people know it can be done.
